spring:
  datasource:
    hikari:
      connection-timeout: 5000
    url: "jdbc:postgresql://localhost:5432/evergreenmedic"
    username: "vaultspay"
    password: "password"
  jpa:
    hibernate:
      #      show-sql: true
      ddl-auto: create-drop
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"

  application:
    name: "evergreenmedic"

  web:
    resources:
      #      static-locations: classpath:/static/
      static-locations: file:./static/

