spring:
  datasource:
    hikari:
      connection-timeout: 5000
    url: "jdbc:postgresql://localhost:5432/evergreenmedic"
    username: "vaultspay"
    password: "password"
  jpa:
    hibernate:
      show-sql: true
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"

  application:
    name: "evergreenmedic"
server:
  port: 8080




